### ISSUE TITLE
Bedaura

### ISSUE THREAD

**Issue by Sixtyi** [TrvsF/wurstplus-two#5] opened 2020-09-17 15:33 UTC
Alright so the bedaura placement and breaks itself and delay are all pretty good sometimes it can be buggy but most of the time its pretty good but there are some issues that ive noticed one that in the src it is supposed to refill the slot with a bed but it does  not so it disables the bedaura this can be fixed with binding hotbarcache on salhack to the same button as bedaura but if the client disables bedaura because there is no player around or or something your hotbarcache will still be on and you have to go into the salhack menu to turn it off and it could happen again because hotbarcache is really annoying when always on because it might mess around with how your hotbar is arranged. now i do realise this is already a bit much to ask but i noticed it doesnt air place if you dont feel like making it airplace thats totally up to you but otherwise good bedaura.

**Comment by TrvsF** [comment] 2020-09-17 16:39
refill will be fixed next update. never tested anything with airplace though, ill look into it if i get the chance

**Comment by Sixtieth** [comment] 2020-09-20 00:50
Trvs did you even debug the bedaura it still  has many bugs with refill. like 1 if you refill a item too fast it will not register that item and it will become a ghost item making the bedaura stuck on trying to place a ghost item

**Comment by TrvsF** [comment] 2020-09-20 13:42
very limited for time rn and only tested it in singleplayer, if the issue is refilling too fast then i recommend turning up the delay

**Closed** 2021-03-16 23:21 UTC
