### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by FaxHack** [TrvsF/wurstplus-two#27] opened 2020-09-27 19:56 UTC
so everytime i try to see player list or press tab i get kicked from server and my game crashes
 and i use wurst+2 by its self and still happends

**Comment by Billy7elal** [comment] 2020-10-03 01:43
this happens when i try to mid click pearl with kami blue, and alot of times it happens for no reason pls fix

**Comment by colmalle** [comment] 2020-11-19 08:53
Duplicate of #24

**Comment by TrvsF** [comment] 2021-03-16 23:19
its a feature

**Closed by TrvsF** 2021-03-16 23:19 UTC
